micronaut:
  server:
    port: 8282
  application:
    name: schoolregistrationmicronaut
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
    jdbc-url: mysql://127.0.0.1:3306/school
    username: root
    password: adminadmin
    hikari:
      connection-timeout: 20000
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 120000
      max-lifetime: 30000
      auto-commit: true
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
